//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportadorDNE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log_Var_Loc
    {
        public int LOC_NU { get; set; }
        public int VAL_NU { get; set; }
        public string VAL_TX { get; set; }
    }
}
