//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportadorDNE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log_Faixa_Uop
    {
        public int UOP_NU { get; set; }
        public int FNC_INICIAL { get; set; }
        public int FNC_FINAL { get; set; }
    }
}
