//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportadorDNE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log_Localidade
    {
        public int LOC_NU { get; set; }
        public string UFE_SG { get; set; }
        public string LOC_NO { get; set; }
        public string CEP { get; set; }
        public string LOC_IN_SIT { get; set; }
        public string LOC_IN_TIPO_LOC { get; set; }
        public Nullable<int> LOC_NU_SUB { get; set; }
        public string LOC_NO_ABREV { get; set; }
        public string MUN_NU { get; set; }
        public Nullable<int> CAD_MUNI_RADAR { get; set; }
    }
}
